In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [88]:
# list
x = [ 5, 10, 15, 20, 25 ]
x.append( 30 )
x.extend( [35, 40] )
x.insert( 2, 99 )
x.remove( 15 )
x.pop( )
print( x.index( 10 ) )
print( x.count( 20 ) )
x.sort( )
x.reverse( )
print( x )
x.clear( )
print( x )

1
1
[99, 35, 30, 25, 20, 10, 5]
[]


In [89]:
# tuple
t = ( "Harshith", "Lucky", "Aditya" )
print("Original tuple:", t)

t_list = list(t)
t_list[1] = "Varun"
t = tuple(t_list)
print("Modified tuple:", t)

Original tuple: ('Harshith', 'Lucky', 'Aditya')
Modified tuple: ('Harshith', 'Varun', 'Aditya')


In [90]:
# set
s= { 1, 2, 2, 3, 4, 4, 5 }
print( s )

{1, 2, 3, 4, 5}


In [91]:
# dict
d= { "name": "Harshith", "age": 20, "city": "Bangalore" }
d[ "age" ] = 21
d[ "email" ]= "harshith@gmail.com"
print( d )

{'name': 'Harshith', 'age': 21, 'city': 'Bangalore', 'email': 'harshith@gmail.com'}


In [92]:
# vote
age= 20
if age >= 18:
    print( "Eligible to vote" )
else:
    print( "Not eligible" )

Eligible to vote


In [93]:
# grade
marks = 85
if marks >= 90:
    print( "A" )
elif marks >= 75:
    print( "B" )
elif marks >= 50:
    print( "C" )
else:
    print( "Fail" )

B


In [94]:
# positive
n= 12
if n > 0:
    if n % 2 == 0:
        print( "Positive and even" )
    else:
        print( "Positive and odd" )
elif n == 0:
    print( "Zero" )
else:
    print( "Negative" )

Positive and even


In [95]:
# numpy
a1 = np.array( 5 )
a2= np.array( [1, 2, 3, 4, 5] )
a3 = np.array( [ [10, 20, 30], [40, 50, 60] ] )
print( a1 )
print( a2 )
print( a3 )

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [96]:
a4= np.random.randint(0, 100, size=(4,4) )
print( a4 )

[[41 36 34 27]
 [66 36 43 95]
 [65 93 50 24]
 [21 35 79 76]]


In [97]:
a5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df= pd.DataFrame( a5, columns= ["A", "B", "C"] )
df

,A,B,C
0,1,2,3
1,4,5,6
2,7,8,9


In [98]:
# pandas
data = {
    "Name": ["Harshith", "Lucky", "Aditya", "Varun", "Srikanth", "Nikhil", "Gree", "Helll", "iaan", "juli"],
    "Age": [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
    "City": ["Hyderabad", "Bangalore", "Chennai", "Delhi", "Delhi", "Mumbai", "Mumbai", "Chennai", "Bangalore", "Chennai"],
    "Salary": [50000.0, 60000.0, np.nan, 70000.0, 80000.0, 90000.0, np.nan, 55000.0, 65000.0, 50000.0]
}
df =pd.DataFrame(data )
df.loc[10] = ["Harshith", 20, "Hyderabad", 50000.0]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    11 non-null     object 
 1   Age     11 non-null     int64  
 2   City    11 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 440.0+ bytes


In [99]:
df.describe()

,Age,Salary
count,11.000000,9.000000
mean,24.090909,63333.333333
std,3.176619,14361.406616
min,20.000000,50000.000000
25%,21.500000,50000.000000
50%,24.000000,60000.000000
75%,26.500000,70000.000000
max,29.000000,90000.000000


In [100]:
df_sub = df[ ["Name", "City"] ]
print( df_sub )
df= df.drop( columns= ["City"] )
m_sal = df["Salary"].mean()
df["Salary"] = df["Salary"].fillna( m_sal )
df= df.drop_duplicates( )
df

        Name       City
0   Harshith  Hyderabad
1      Lucky  Bangalore
2     Aditya    Chennai
3      Varun      Delhi
4   Srikanth      Delhi
5     Nikhil     Mumbai
6       Gree     Mumbai
7      Helll    Chennai
8       iaan  Bangalore
9       juli    Chennai
10  Harshith  Hyderabad


,Name,Age,Salary
0,Harshith,20,50000.000000
1,Lucky,21,60000.000000
2,Aditya,22,63333.333333
3,Varun,23,70000.000000
4,Srikanth,24,80000.000000
5,Nikhil,25,90000.000000
6,Gree,26,63333.333333
7,Helll,27,55000.000000
8,iaan,28,65000.000000
9,juli,29,50000.000000
